########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryConsoleApplication(
        target      = 'AzCodeGeneratorUnitTests',
        vs_filter   = 'Tools',
        file_list   = 'azcodegeneratorunittests.waf_files',
        platforms  = ['win_x64', 'darwin_x64', 'linux_x64'],
        configurations = ['debug_test', 'profile_test'],

        use = ['AzCore'],

        features = ['az_code_gen'],
        az_code_gen = [
            {
                'files' : [bld.srcnode.find_or_declare('Code/Framework/AzCore/Tests/CodeGen.h')],
                'scripts' : [
                    '../../../Framework/AzFramework/CodeGen/AzClassCpp.py', 
                    #'../../../Framework/AzFramework/CodeGen/AzEBusInline.py', 
                    '../../../Framework/AzFramework/CodeGen/AzReflectionCpp.py', 
                    '../../../Framework/AzFramework/CodeGen/AzClassInline.py'
                ],
                'arguments' : [
                               #'-OnlyRunDiagnosticsOnMainFile=false',
                               #'-SuppressDiagnostics=false',
                               #'-SuppressErrorsAsWarnings=false',
                               #'-output-redirection=file',
                               # Diagnostics:
                               #'-SuppressIncludeNotFoundError=false',
                               #'-SkipFunctionBodies=false',
                               #'-DelayedTemplateParsing=false',
                               #'-EnableIncrementalProcessing=false',
                              ],
                #'options' : ['PrintOutputRedirectionFile']
            }
        ]
    )
