########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryLauncher(
        #==============================
        # Settings
        #==============================
        target           = 'MacLauncher',
        vs_filter        = 'Game/Launcher',
        file_list        = 'maclauncher.waf_files',
        platforms        = ['darwin'],
        configurations   = ['debug', 'debug_test', 'profile', 'profile_test', 'performance', 'release'],
        mac_launcher     = True,

        #==============================
        # Common
        #==============================
        includes        = [ bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Launcher/AppleLaunchersCommon'),
                            bld.Path('Code/SDKs/SDL2/include/mac') ],
        use = ['AzGameFramework', 'LmbrCentral'],

        lib     = [ 'SDL2', 
                    'tommath',
                    'tomcrypt'], 
        libpath = [ bld.Path('Code/SDKs/LibTomCrypt/lib/mac'),
                    bld.Path('Code/SDKs/LibTomMath/lib/mac'),
                    bld.Path('Code/SDKs/SDL2/lib/mac')],
        rpath = [ "@executable_path/" ],

        cxxflags = [ '-x', 'objective-c++' ],
    )
