########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryDedicatedServer(
        target      = 'DedicatedLauncher', 
        vs_filter   = 'Game/Launcher',
        platforms   = ['win_x64'],
        configurations = ['debug_dedicated', 'debug_test_dedicated', 'profile_dedicated', 'profile_test_dedicated', 
                          'performance_dedicated', 'release_dedicated'],
        use         = ['CryRenderNULL',
                       'AzGameFramework'],

        profile_all_defines = ['AZ_DEBUG_BUILD'],
        
        file_list   = 'launcher.waf_files', 
        lib         = 'Shell32', 
    )
