########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryPluginModule(
        #==============================
        # Settings
        #==============================
        target                      = 'FbxSDKWrapper',
        vs_filter                   = 'Tools/SceneAPI',
        file_list                   = 'fbxsdkwrapper.waf_files',
        platforms                   = ['win'],
        configurations              = ['debug', 'debug_test', 'profile', 'profile_test'],

        #==============================
        # Common
        #==============================
        includes                    = [ '.',
                                        bld.Path('Code/Tools'),
                                        bld.Path('Code/Tools/RC/ResourceCompiler'),
                                        bld.Path('Code/Tools/CryCommonTools'),
                                        bld.Path('Code/SDKs/FbxSdk/include') ],
        use         = [ 'AzCore', 'AzFramework' ],
        libpath     = [ bld.Path('Code/Tools/CryCommonTools') ],

        test_all_file_list = 'fbxsdkwrapper_testing.waf_files',
        win_lib     = [ 'libfbxsdk-md', 'dbghelp', 'Wininet' ],

        win_x86_debug_all_libpath        = bld.Path('Code/SDKs/FbxSdk/lib/vs2013/x86/debug'),
        win_x86_ndebug_libpath           = bld.Path('Code/SDKs/FbxSdk/lib/vs2013/x86/release'),
        
        win_x64_debug_all_libpath        = bld.Path('Code/SDKs/FbxSdk/lib/vs2013/x64/debug'),
        win_x64_ndebug_libpath           = bld.Path('Code/SDKs/FbxSdk/lib/vs2013/x64/release'),
    )
