########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):
    bld.CryResourceCompilerModule(

        #==============================
        # Settings
        #==============================
        target              = 'ResourceCompilerXML',
        vs_filter           = 'RC',
        file_list           = 'resourcecompilerxml.waf_files',
        platforms           = ['win'],
        configurations      = ['debug_all', 'profile_all'],

        #==============================
        # Common
        #==============================
        includes                = [ '.',
                                    bld.Path('Code/Tools'),
                                    bld.Path('Code/Tools/RC/ResourceCompiler'),
                                    bld.Path('Code/Tools/CryCommonTools'),
                                    bld.Path('Code/Tools/CryXML'),
                                    bld.Path('Code/CryEngine/CrySystem/XML'),
                                    bld.Path('Code/Sandbox/SDKs/Qt/include/ActiveQt'),
                                    bld.Path('Code/Sandbox/SDKs/Qt/include/QtANGLE')],

        autod_uselib            = [ 'QT5CORE',
                                    'QT5GUI',
                                    'QT5NETWORK',
                                    'QT5QML',
                                    'QT5QUICK',
                                    'QT5WIDGETS'],

        use                     = ['AzToolsFramework'],
                                
        libpath			        = bld.Path('Code/Tools/CryCommonTools'),
        export_definitions	    = 'ResourceCompilerPlugin.def',
        
        #==============================
        # Testing
        #==============================
        test_all_file_list  = ['resourcecompilerxml_test.waf_files'],
    )