{#
All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or 
its licensors.

For complete copyright and license terms please see the LICENSE at the root of this
distribution (the "License"). All use of this software is governed by the License,
or, if provided, by the license below or the license accompanying this file. Do not
remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#}
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
// THIS CODE IS AUTOGENERATED, DO NOT MODIFY
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
#include "StdAfx.h"

// This code creates AZ::Modules for use in a monolithic build.
#if AZ_MONOLITHIC_BUILD

#include <AzCore/std/containers/vector.h>

namespace AZ
{
    class Module;
}

{% for module in json_object.modules %}
extern "C" AZ::Module* CreateModuleClass_{{ module }}();
{% endfor %}

extern "C" void CreateStaticModules(AZStd::vector<AZ::Module*>& modulesOut)
{
    {% for module in json_object.modules %}
    modulesOut.push_back(CreateModuleClass_{{ module }}());
    {% endfor %}
}

#endif // AZ_MONOLITHIC_BUILD
