########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

from waflib.TaskGen import feature

def build(bld):
    bld.CryResourceCompilerModule(
        target                  = 'ResourceCompilerScene',
        vs_filter               = 'RC',
        file_list               = 'resourcecompilerscene.waf_files',
        
        platforms               = ['win'],
        configurations          = ['debug_all', 'profile_all'],
        includes                = [ '.',
                                    bld.Path('Code/Tools'),
                                    bld.Path('Code/Tools/RC/ResourceCompiler'),
                                    bld.Path('Code/Tools/CryCommonTools'),
                                    bld.Path('Code/SDKs/zlib-common')
                                  ],
        use                     = [ 'AzCore', 'AzFramework', 'AzToolsFramework', 'GFxFramework', 'SceneCore', 'SceneData', 'FbxSceneBuilder' ],
        features            	= [ 'qt5' ],
        autod_uselib            = ['QT5CORE', 'QT5GUI', 'QT5WIDGETS'],
        export_definitions      = 'ResourceCompilerScenePlugin.def',
        
        test_all_file_list    = 'resourcecompilerscene_tests.waf_files',
    )