########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.env.LIB_OPENVR      = ['openvr_api']
    bld.env.LIBPATH_OPENVR  = [bld.Path('Code/SDKs/OpenVR/lib/win64')]
    bld.env.INCLUDES_OPENVR = [bld.Path('Code/SDKs/OpenVR/headers')]

    bld.DefineGem(
        includes    = [bld.Path('Code/CryEngine/CryCommon'),
                       bld.Path('Code/CryEngine/CryAction')],

        # OpenVR is defined for windows only.
        win_use         = ['OPENVR'],
        win_file_list   = ['openvr_win.waf_files'],
        win_features    = [ 'copy_dependent_libs' ],
        source_artifacts_include = [ 'Code/SDKs/OpenVR/bin/win64/openvr_api.dll'],
    )
