########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryResourceCompiler(
        #==============================
        # Settings
        #==============================
        target          = 'ResourceCompiler',
        vs_filter       = 'RC',
        file_list       = 'resourcecompiler.waf_files',
        platforms       = ['win'],
        configurations  = ['debug_all', 'profile_all'],

        #==============================
        # Common
        #==============================
        features        = [ 'qt5'],

        use             = [ 'zlib',
                            'AzToolsFramework',
                            'AzFramework'],

        defines         = [ 'NOT_USE_CRY_MEMORY_MANAGER',
                            'TOOLS_SUPPORT_DURANGO',
                            'TOOLS_SUPPORT_ORBIS'],

        includes        = [ '.',
                            bld.Path('Code/Tools/CryCommonTools'),
                            bld.Path('Code/Tools/CryXML'),
                            bld.Path('Code/CryEngine/CrySystem/XML')],

        autod_uselib    = [ 'QT5CORE',  'QT5GUI',  'QT5WIDGETS'],

        libpath         = [	bld.Path('Code/Tools/CryCommonTools'),
                            bld.Path('Code/Sandbox/SDKs/Qt/lib') ],

        lib             = [ 'psapi', 'dbghelp'],

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['resourcecompiler_test.waf_files'],
    )
