########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):


    bld.CryStandAlonePlugin(

        # Substance is only supported on windows
        win_defines = ['USE_SUBSTANCE'],

        #==============================
        # Settings
        #==============================
        target          = 'ProceduralMaterialEditorPlugin',
        vs_filter       = 'Sandbox/Plugins',
        file_list       = 'proceduralmaterialeditorplugin.waf_files',
        platforms       = ['win'],
        configurations  = ['debug', 'debug_test', 'profile', 'profile_test'],

        use	            = ['EditorCommon','EditorCore'],
        features	    = 'qt5',

        #==============================
        # Common
        #==============================
        includes = [bld.Path('Code/CryEngine/CryCommon'),
                    bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                    bld.Path('Code/CryEngine/CryAction'),
                    bld.Path('Code/Sandbox/SDKs/Qt/include/QtANGLE'),
                    bld.Path('Gems/Substance/Code/Include') ],

        autod_uselib    = [ 'QT5CORE',
                            'QT5GUI',
                            'QT5WIDGETS'],


        defines         = ['QT_NO_DEBUG',
                           'QT_LARGEFILE_SUPPORT',
                           'QT_DLL',
                           'QT_NO_EMIT',
                           'EDITOR_COMMON_IMPORTS'],

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['proceduralmaterialeditorplugin_test.waf_files'],
    )


