########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryResourceCompilerModule(
        #==============================
        # Settings
        #==============================
        target                      = 'ResourceCompilerSlice',
        vs_filter                   = 'RC',
        file_list                   = 'resourcecompilerslice.waf_files',
        platforms                   = ['win'],
        configurations              = ['debug_all', 'profile_all'],

        build_in_dedicated          = False, # not used by dedicated server

        #==============================
        # Common
        #==============================
        use                         = ['AzToolsFramework', 'LmbrCentral', 'LmbrCentralEditor'],
        features                    = ['qt5'],
        autod_uselib                = ['QT5CORE', 'QT5GUI', 'QT5WIDGETS'],

        includes                    = [ '.',
                                        bld.Path('Code/Tools'),
                                        bld.Path('Code/Tools/RC/ResourceCompiler'),
                                        bld.Path('Code/Tools/CryCommonTools')],

        export_definitions          = 'ResourceCompilerPlugin.def',

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['resourcecompilerslice_test.waf_files'],
    )
