########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryLauncher(
        #==============================
        # Settings
        #==============================
        target           = 'AppleTVLauncher',
        vs_filter        = 'Game/Launcher',
        file_list        = 'appletvlauncher.waf_files',
        platforms        = ['appletv'],
        configurations   = ['debug', 'profile', 'performance', 'release'],
        appletv_launcher = True,
        use              = ['AzGameFramework'],

        #==============================
        # Common
        #==============================
        includes        = [ bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Launcher/AppleLaunchersCommon') ],

        lib     = [ 'tommath',
                    'tomcrypt',
                    'freetype' ],

        libpath = [ bld.Path('Code/SDKs/LibTomCrypt/lib/appletv'),
                    bld.Path('Code/SDKs/LibTomMath/lib/appletv'),
                    bld.Path('Code/SDKs/FreeType2/ios/lib') ],
        cxxflags        = [ '-x', 'objective-c++' ],
    )
