########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.AndroidLauncher(
        project_name                            = '%%%ANDROID_PROJECT_NAME%%%',
        project_manifest                        = 'main/AndroidManifest.xml',
        project_resources                       = 'main/res',

        java_source_path                        = [ 'main/java' ],
        android_armv7_gcc_java_source_path      = [ 'android_armv7_gcc/java' ],
        android_armv7_clang_java_source_path    = [ 'android_armv7_clang/java' ],

        java_code_gen_dir                       = 'main/gen',
    )


