########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS = [
        'EditorPlugin'
    ]

def build(bld):

    bld.DefineGem(
        includes    = [ bld.Path('Code/CryEngine/CryAction'),
                        bld.Path('Code/SDKs/Substance/include')],
        file_list   = ['Substance.waf_files'],

        # This is necessary for Orbis because there is an indirect reference (via CryCommon\ImageExtensionHelper.h) to a RenderDll internal header
       

		# Substance is only supported on windows
		win_defines = ['USE_SUBSTANCE'],

        disable_tests = not 'win' in bld.env['PLATFORM'],
        features    = [ 'copy_dependent_libs' ],
        source_artifacts_include = [ 'Code/SDKs/Substance/bin/win32-msvc2013-64/release_md/substance_sse2.dll',
                                     'Code/SDKs/Substance/bin/win32-msvc2013-64/release_md/substance_d3d10.dll',
                                     'Code/SDKs/Substance/bin/win32-msvc2013-64/release_md/substance_d3d11.dll']
    )

    bld.recurse(SUBFOLDERS)
