########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    platform = bld.env['PLATFORM']
    enable_tests = ('win' in platform and 'darwin' not in platform) or platform == 'project_generator'

    # GemRegistry has no windows resources, so it does not need to be passed to windows RC.EXE
    # thus it is a non-rc module.

    bld.CryEngineModule(
        target          = 'GemRegistry',
        vs_filter       = 'Tools',
        file_list       = 'gemregistry.waf_files',
        platforms       = ['all'],
        configurations  = ['all'],

        includes        = ['include',
                           'source'],
        export_includes = ['include'],
        use             = ['AzFramework'],
        win_lib         = ['shlwapi'],
        
        #==============================
        # Testing
        #==============================
        test_all_file_list = ['gemregistry_test.waf_files'],
    )
