########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        # Add custom build options here
		use         = ['GridMate'],
        includes    = [bld.Path('Code/CryEngine/CryAction'),
                       bld.Path('Code/CryEngine/CryNetwork')],
        pch = '',
        debug_defines = ['AZ_DEBUG_BUILD'],
        profile_defines = ['AZ_DEBUG_BUILD'],
        debug_dedicated_defines = ['AZ_DEBUG_BUILD'],
        profile_dedicated_defines = ['AZ_DEBUG_BUILD'],
        file_list       = ['CertificateManager.waf_files'],

        #==============================
        # Windows
        #==============================
        win_features    = ['AWSNativeSDK'],
        win_use         = bld.make_aws_library_task_list(['aws-cpp-sdk-core','aws-cpp-sdk-s3']),
        win_lib         = ['gdi32', 'WinHTTP', 'Ws2_32', 'mswsock'],
       
       
    )
