########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

SUBFOLDERS = [
    'NewsBuilder'
]

# Dependent files/folders from Bin64 to copy to any other target folder
INCLUDE_MIRROR_EDITOR_FILES = [
    'QT*.dll',
    'qtlibs'
]

def build(bld):
    for subfolder in SUBFOLDERS:
        bld.recurse([subfolder], mandatory = False)
     
    bld.CryEngineStaticLibrary(
        target          = 'NewsShared',
        vs_filter       = 'Tools/News',
        file_list       = 'news_shared.waf_files',
        export_includes = '.', 
        platforms       = ['win'],
        configurations  = ['debug', 'debug_test', 'profile', 'profile_test'],
        features        = ['qt5'],
        autod_uselib    = [ 'QT5CORE',
                            'QT5GUI',
                            'QT5NETWORK',
                            'QT5WIDGETS' ],
        win_libpath = [ bld.Path('Code/Sandbox/SDKs/Qt/lib') ]
    )
    