########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def configure(cfg):
    pass

def build(bld):
    bld.LumberyardApp(
        target      = 'GFXPrefabLab',
        file_list   = ['common.waf_files', 'gui.waf_files'],
        vs_filter   = 'GFXPrefabLab',

        use         = ['AzToolsFramework'],
        includes    = ['.'],
        defines     = [],

        features    = ['qt5'],
        #qt_to_moc_files = [
        #                    "gui/mainwindow.h",
        #                   ],

        autod_uselib = [ 'QT5CORE',
                         'QT5QUICK',
                         'QT5WIDGETS',
                         'QT5SVG',
                         'QT5NETWORK',
                         'QT5GUI',
                         'QT5QUICKWIDGETS',
                         'QT5QML',
                         'QT5XML'],
    )
