########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.env.LIB_OVR      = ['LibOVR']
    bld.env.LIBPATH_OVR  = [bld.Path('Code/SDKs/OculusSDK/LibOVR/Lib/Windows/x64/Release/VS2013')]
    bld.env.INCLUDES_OVR = [bld.Path('Code/SDKs/OculusSDK/LibOVR/Include')]

    bld.DefineGem(
        includes    = [bld.Path('Code/CryEngine/CryCommon'), 
                       bld.Path('Code/CryEngine/CryAction')],

       # Oculus is defined for windows only.
        win_use       = ['OVR'],
        win_file_list = ['oculus_win.waf_files'],
    )
